


server:
  port: 7003



spring:
  elasticsearch:
    rest:
      uris: http://192.168.200.100:9200

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration